server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://ep-holy-heart-a58jnnwh.us-east-2.aws.neon.tech/saleapp
    driver-class-name: org.postgresql.Driver
    username: saleapp_owner
    password: yp8tDSnX6vjF
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  message:
    basename: i18n/message
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 ngày = 2592000 giây
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

logging.level.org.springframework.security: DEBUG

